
version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: squares_and_circles_development
    ports:
      - "3309:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && ./bin/rails db:create db:migrate && ./bin/rails s -b 0.0.0.0"
    volumes:
      - .:/rails
      - gem-cache:/usr/local/bundle/gems
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql2://root:password@db/squares_and_circles_development
      - RAILS_ENV=development

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
      - swagger-ui

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      URL: /swagger.yml
    volumes:
      - ./swagger.yml:/usr/share/nginx/html/swagger.yml

  swagger-gen:
    build: .
    command: bash -c "gem install rswag-cli && rswag-specs"
    volumes:
      - .:/rails

volumes:
  mysql-data:
  gem-cache:
