
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: squares_and_circles_development
    ports:
      - "3309:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build:
      context: .
      args:
        RAILS_ENV: development
        BUNDLE_WITHOUT: ""
    command: ["./wait-for-it.sh", "db", "bash", "-c", "rm -f tmp/pids/server.pid && ./bin/rails db:create db:migrate && ./bin/rails s -b 0.0.0.0"]
    volumes:
      - .:/rails
      - gem-cache:/usr/local/bundle/gems
      - ./wait-for-it.sh:/rails/wait-for-it.sh
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql2://root:password@db/squares_and_circles_development
      - RAILS_ENV=development

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
      - swagger-ui

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      URLS: "[ { url: '/api-docs/v1/swagger.yaml', name: 'API V1' } ]"
    volumes:
      - ./public/api-docs/v1/swagger.yaml:/usr/share/nginx/html/api-docs/v1/swagger.yaml

  swagger-gen:
    build:
      context: .
      args:
        RAILS_ENV: development
        BUNDLE_WITHOUT: ""
    command: ["./wait-for-it.sh", "db", "bash", "-c", "bundle install && bundle exec rails g rspec:install && bundle exec rspec spec/requests && cp -r public/api-docs/* /swagger-docs"]
    volumes:
      - .:/rails
      - swagger-docs:/swagger-docs
      - ./wait-for-it.sh:/rails/wait-for-it.sh
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql2://root:password@db/squares_and_circles_development
      - RAILS_ENV=development

volumes:
  mysql-data:
  gem-cache:
  swagger-docs:
