---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/":
    get:
      summary: root path
      tags:
      - Application
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  "/frames/{frame_id}/circles":
    post:
      summary: Creates a Circle within a Frame
      tags:
      - Circles
      parameters:
      - name: frame_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '201':
          description: circle created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                circle:
                  type: object
                  properties:
                    center_x:
                      type: number
                    center_y:
                      type: number
                    diameter:
                      type: number
                  required:
                  - center_x
                  - center_y
                  - diameter
              required:
              - circle
  "/circles":
    get:
      summary: Searches for Circles
      tags:
      - Circles
      parameters:
      - name: center_x
        in: query
        required: false
        schema:
          type: number
      - name: center_y
        in: query
        required: false
        schema:
          type: number
      - name: radius
        in: query
        required: false
        schema:
          type: number
      - name: frame_id
        in: query
        required: false
        schema:
          type: integer
      responses:
        '200':
          description: circles found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    center_x:
                      type: number
                    center_y:
                      type: number
                    diameter:
                      type: number
                    frame_id:
                      type: integer
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time
  "/circles/{id}":
    put:
      summary: Updates a Circle
      tags:
      - Circles
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: circle updated
        '422':
          description: invalid request
        '404':
          description: circle not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                circle:
                  type: object
                  properties:
                    center_x:
                      type: number
                    center_y:
                      type: number
                    diameter:
                      type: number
    delete:
      summary: Deletes a Circle
      tags:
      - Circles
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: circle deleted
        '404':
          description: circle not found
  "/frames":
    post:
      summary: Creates a Frame
      tags:
      - Frames
      parameters: []
      responses:
        '201':
          description: frame created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                frame:
                  type: object
                  properties:
                    center_x:
                      type: number
                    center_y:
                      type: number
                    width:
                      type: number
                    height:
                      type: number
                    circles_attributes:
                      type: array
                      items:
                        type: object
                        properties:
                          center_x:
                            type: number
                          center_y:
                            type: number
                          diameter:
                            type: number
                        required:
                        - center_x
                        - center_y
                        - diameter
                  required:
                  - center_x
                  - center_y
                  - width
                  - height
              required:
              - frame
    get:
      summary: Retrieves all Frames
      tags:
      - Frames
      responses:
        '200':
          description: frames found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    center_x:
                      type: number
                    center_y:
                      type: number
                    width:
                      type: number
                    height:
                      type: number
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time
  "/frames/{id}":
    get:
      summary: Retrieves a Frame
      tags:
      - Frames
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: frame found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  center_x:
                    type: number
                  center_y:
                    type: number
                  width:
                    type: number
                  height:
                    type: number
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
                  circles:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        center_x:
                          type: number
                        center_y:
                          type: number
                        diameter:
                          type: number
                        frame_id:
                          type: integer
                        created_at:
                          type: string
                          format: date-time
                        updated_at:
                          type: string
                          format: date-time
        '404':
          description: frame not found
    put:
      summary: Updates a Frame
      tags:
      - Frames
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: frame updated
        '422':
          description: invalid request
        '404':
          description: frame not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                frame:
                  type: object
                  properties:
                    center_x:
                      type: number
                    center_y:
                      type: number
                    width:
                      type: number
                    height:
                      type: number
    delete:
      summary: Deletes a Frame
      tags:
      - Frames
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: frame deleted
        '404':
          description: frame not found
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
